apiVersion: v1
kind: Service
metadata:
  name: tornjak-actual
  labels:
    name: tornjak
spec:
  selector:
      name: tornjak
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
