config:
  connectors:
  # ldap connector config
  - config:
      bindDN: cn=admin,dc=example,dc=org
      bindPW: adminpassword
      groupSearch:
        baseDN: dc=example,dc=org
        filter: (objectClass=groupOfNames)
        nameAttr: cn
        userMatchers:
        - groupAttr: member
          userAttr: DN
      host: openldap.openldap:1389 # servicename.namespacename:portnumber
      insecureNoSSL: true
      insecureSkipVerify: true
      startTLS: false
      userSearch:
        baseDN: ou=users,dc=example,dc=org
        emailAttr: uid
        filter: (objectClass=inetOrgPerson)
        idAttr: uid
        nameAttr: uid
        preferredUsernameAttr: uid
        username: uid
    id: ldap
    name: LDAP
    type: ldap
  # dex config
  issuer: http://dex.dex:5556/dex # url dex will be available on
  logger:
    format: text
    level: info
  oauth2:
    skipApprovalScreen: true
  storage:
    type: memory # in memory storage
  web:
    http: 0.0.0.0:8080 # port dex is going to listen on for clients to connect to
  # oauth client config
  staticClients:
  - id: kasten
    name: OAuth2Proxy
    redirectURIs:
    - http://oauth2-proxy.tornjak:4180/oauth2/callback # oAuth2 proxy redirect url
    secret: kastensecret
